create type field as enum ('short_text', 'long_text');
create table tool_fields (
        id int generated by default as identity primary key,
        tool_id int not null,
        foreign key (tool_id) references tools(id) on delete cascade,
        order_index int not null,
        field_type field not null,
        label text not null default ''
);
